name: Vérification sondage

on:
  schedule:
    # Toutes les heures
    - cron: "0 * * * *"

  # Permet de lancer le workflow à la main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-poll:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Lancer la vérification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python scripts/check_poll.py

      - name: Sauvegarder les changements
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add sondage.json

          git diff --cached --quiet || git commit -m "Fin automatique du sondage"

          git push
